using System.IO;
using System.Windows.Forms;
using Newtonsoft.Json;

namespace SAModel.SAEditorCommon.Import
{
	/// <summary>
	/// This class is used for import or export of models and animations from/to SAModel or other formats.
	/// </summary>
	public static class ModelImportExport
	{
		/// <summary>
		/// Creates an "export model" dialog with all the supported filters.
		/// This doesn't do the actual export, it only displays the dialog and returns the filename.
		/// </summary>
		/// <param name="model">NJS_OBJECT to export, used to retrieve the model name and format.</param>
		/// <param name="modelName">Model filename without extension, can be empty or null.</param>
		/// <returns>The full path entered in the dialog, or an empty string.</returns>
		public static string ExportModelDialog(NJS_OBJECT model, string modelName)
		{
			// Default name
			if (string.IsNullOrEmpty(modelName))
				modelName = model.Name;
			// Extension
			string defaultex = model.GetModelFormat() switch
			{
				ModelFormat.Chunk => ".sa2mdl",
				ModelFormat.GC => ".sa2bmdl",
				ModelFormat.XJ => ".xj",
				_ => ".sa1mdl",
			};
			// Create dialog
			using SaveFileDialog a = new SaveFileDialog
			{
				FileName = modelName + defaultex,
				Filter = "SAModel Files|*.sa?mdl|Ninja Binary|*.nj;*.gj|Collada|*.dae|Wavefront|*.obj|FBX|*.fbx"
			};
			// Return filename
			return a.ShowDialog() == DialogResult.OK ? a.FileName : string.Empty;
		}

		/// <summary>
		/// Exports the specified NJS_OBJECT to a file. The format is determined by file extension.
		/// </summary>
		/// <param name="model">NJS_OBJECT to export.</param>
		/// <param name="exportPath">Path to the exported model file.</param>
		/// <param name="matrix">SharpDX transform matrix (doesn't do anything currently).</param>
		/// <param name="texinfo">Array of texture names, can be null.</param>
		/// <param name="modelDescription">Model description, can be empty or null.</param>
		/// <returns>The full path to the exported file, or an empty string.</returns>
		public static void ExportModel(NJS_OBJECT model, string exportPath, SharpDX.Matrix matrix, string[] texinfo = null, string modelDescription = null)
		{
			string ftype; // Export format string for Assimp
			switch (System.IO.Path.GetExtension(exportPath).ToLowerInvariant())
			{
				case ".fbx":
					ftype = "fbx";
					break;
				case ".obj":
					ftype = "obj";
					break;
				case ".dae":
					ftype = "collada";
					break;
				case ".nj":
				case ".gj":
				case ".xj":
					ModelFile.CreateFile(exportPath, model, null, null, modelDescription, null, model.GetModelFormat(), useNinjaMetaData: true);
					return;
				case ".sa1mdl":
				case ".sa2mdl":
				case ".sa2bmdl":
				default:
					ModelFile.CreateFile(exportPath, model, null, null, modelDescription, null, model.GetModelFormat());
					return;
			}
			Assimp.AssimpContext context = new Assimp.AssimpContext();
			Assimp.Scene scene = new Assimp.Scene();
			scene.Materials.Add(new Assimp.Material());
			Assimp.Node n = new Assimp.Node();
			n.Name = "RootNode";
			scene.RootNode = n;
			AssimpStuff.AssimpExport(model, scene, matrix, texinfo ?? null, scene.RootNode);
			context.ExportFile(scene, exportPath, ftype, Assimp.PostProcessSteps.ValidateDataStructure | Assimp.PostProcessSteps.Triangulate | Assimp.PostProcessSteps.FlipUVs);
		}

		/// <summary>
		/// Exports an NJS_MOTION to an .saanim, .c or .json file (WIP).
		/// </summary>
		/// <param name="motion">NJS_MOTION to export.</param>
		/// <param name="motionFilename">Default motion filename (can be empty or null).</param>
		public static void ExportAnimation(NJS_MOTION motion, string motionFilename)
		{
			if (string.IsNullOrEmpty(motionFilename))
				motionFilename = motion.Name;
			using (System.Windows.Forms.SaveFileDialog a = new System.Windows.Forms.SaveFileDialog
			{
				FileName = motionFilename + ".saanim",
				Filter = "SAModel Animations|*.saanim|JSON|*.json|C structs|*.c"
			})
			{
				if (a.ShowDialog() == System.Windows.Forms.DialogResult.OK)
				{
					switch (System.IO.Path.GetExtension(a.FileName).ToLowerInvariant())
					{
						case ".c":
						case ".txt":
							using (System.IO.StreamWriter sw = System.IO.File.CreateText(a.FileName))
							{
								sw.WriteLine("/* NINJA Motion");
								sw.WriteLine(" * ");
								sw.WriteLine(" * Generated by SA Tools");
								sw.WriteLine(" * ");
								sw.WriteLine(" */");
								sw.WriteLine();
								motion.ToStructVariables(sw);
								sw.Flush();
								sw.Close();
							}
							break;
						case ".json":
							Newtonsoft.Json.JsonSerializer js = new Newtonsoft.Json.JsonSerializer() { Culture = System.Globalization.CultureInfo.InvariantCulture };
							using (TextWriter tw = File.CreateText(a.FileName))
							using (JsonTextWriter jtw = new JsonTextWriter(tw) { Formatting = Formatting.Indented })
								js.Serialize(jtw, motion);
							break;
						case ".saanim":
						default:
							motion.Save(a.FileName);
							break;
					}
				}
			}
		}

		/*
		/// <summary>
		/// Import a model (unfinished)
		/// </summary>
		/// <param name="format"></param>
		/// <param name="importAsSingleModel"></param>
		/// <param name="texinfo"></param>
		/// <param name="steps"></param>
		/// <returns></returns>
		public static NJS_OBJECT ImportModel(ModelFormat format, bool importAsSingleModel, string[] texinfo = null, Assimp.PostProcessSteps steps = Assimp.PostProcessSteps.Triangulate | Assimp.PostProcessSteps.JoinIdenticalVertices | Assimp.PostProcessSteps.FlipUVs)
		{
			OpenFileDialog dlg = new OpenFileDialog() { DefaultExt = "sa1mdl", Filter = "Model Files|*.sa*mdl;*.obj;*.objf;*.dae;*.fbx", RestoreDirectory = true };
			if (dlg.ShowDialog() == DialogResult.OK)
			{

				//if (LevelData.TextureBitmaps != null && LevelData.TextureBitmaps[LevelData.leveltexs] != null)

				switch (Path.GetExtension(dlg.FileName).ToLowerInvariant())
				{
					case ".obj":
					case ".fbx":
					case ".dae":
					case ".objf":
						Assimp.AssimpContext context = new Assimp.AssimpContext();
						context.SetConfig(new Assimp.Configs.FBXPreservePivotsConfig(false));
						Assimp.Scene scene = context.ImportFile(dlg.FileName, steps);
						return AssimpStuff.AssimpImport(scene, scene.RootNode, format, texinfo, importAsSingleModel);
					case ".sa1mdl":
						ModelFile mf = new ModelFile(dlg.FileName);
						return mf.Model;
				}
			}
			return null;
		}

		public static string[] ExportLevelTextures(string modelFilename)
		{
			string rootPath = System.IO.Path.GetDirectoryName(modelFilename);
			List<string> texturePaths = new List<string>();
			int numSteps = 0;
			if (LevelData.TextureBitmaps != null && LevelData.TextureBitmaps.Count > 0)
			{
				numSteps = LevelData.TextureBitmaps[LevelData.leveltexs].Length;
			}
			for (int i = 0; i < numSteps; i++)
			{
				BMPInfo bmp = LevelData.TextureBitmaps[LevelData.leveltexs][i];
				texturePaths.Add(System.IO.Path.Combine(rootPath, bmp.Name + ".png"));
				bmp.Image.Save(System.IO.Path.Combine(rootPath, bmp.Name + ".png"));
			}
			return texturePaths.ToArray();
		}
		*/
	}
}