@echo EXE split
..\..\bin\split binary data/sonic2app.exe Characters.ini output/
..\..\bin\split binary data/sonic2app.exe Enemies.ini output/
..\..\bin\split binary data/sonic2app.exe CommonObjects.ini output/
..\..\bin\split binary data/sonic2app.exe ADVERTISE.ini output/
..\..\bin\split binary data/sonic2app.exe EMBLEMGET.ini output/
..\..\bin\split binary data/sonic2app.exe STG00.ini output/
..\..\bin\split binary data/sonic2app.exe STG03.ini output/
..\..\bin\split binary data/sonic2app.exe STG04.ini output/
..\..\bin\split binary data/sonic2app.exe STG05.ini output/
..\..\bin\split binary data/sonic2app.exe STG06.ini output/
..\..\bin\split binary data/sonic2app.exe STG07.ini output/
..\..\bin\split binary data/sonic2app.exe STG08.ini output/
..\..\bin\split binary data/sonic2app.exe STG09.ini output/
..\..\bin\split binary data/sonic2app.exe STG10.ini output/
..\..\bin\split binary data/sonic2app.exe STG11.ini output/
..\..\bin\split binary data/sonic2app.exe STG12.ini output/
..\..\bin\split binary data/sonic2app.exe STG13.ini output/
..\..\bin\split binary data/sonic2app.exe STG14.ini output/
..\..\bin\split binary data/sonic2app.exe STG15.ini output/
..\..\bin\split binary data/sonic2app.exe STG16.ini output/
..\..\bin\split binary data/sonic2app.exe STG17.ini output/
..\..\bin\split binary data/sonic2app.exe STG18.ini output/
..\..\bin\split binary data/sonic2app.exe STG19.ini output/
..\..\bin\split binary data/sonic2app.exe STG20.ini output/
..\..\bin\split binary data/sonic2app.exe STG21.ini output/
..\..\bin\split binary data/sonic2app.exe STG22.ini output/
..\..\bin\split binary data/sonic2app.exe STG23.ini output/
..\..\bin\split binary data/sonic2app.exe STG24.ini output/
..\..\bin\split binary data/sonic2app.exe STG25.ini output/
..\..\bin\split binary data/sonic2app.exe STG26.ini output/
..\..\bin\split binary data/sonic2app.exe STG27.ini output/
..\..\bin\split binary data/sonic2app.exe STG28.ini output/
..\..\bin\split binary data/sonic2app.exe STG29.ini output/
..\..\bin\split binary data/sonic2app.exe STG30.ini output/
..\..\bin\split binary data/sonic2app.exe STG31.ini output/
..\..\bin\split binary data/sonic2app.exe STG32.ini output/
..\..\bin\split binary data/sonic2app.exe STG33.ini output/
..\..\bin\split binary data/sonic2app.exe STG34.ini output/
..\..\bin\split binary data/sonic2app.exe STG35.ini output/
..\..\bin\split binary data/sonic2app.exe STG36.ini output/
..\..\bin\split binary data/sonic2app.exe STG37.ini output/
..\..\bin\split binary data/sonic2app.exe STG38.ini output/
..\..\bin\split binary data/sonic2app.exe STG39.ini output/
..\..\bin\split binary data/sonic2app.exe STG40.ini output/
..\..\bin\split binary data/sonic2app.exe STG41.ini output/
..\..\bin\split binary data/sonic2app.exe STG42.ini output/
..\..\bin\split binary data/sonic2app.exe STG43.ini output/
..\..\bin\split binary data/sonic2app.exe STG44.ini output/
..\..\bin\split binary data/sonic2app.exe STG45.ini output/
..\..\bin\split binary data/sonic2app.exe STG46.ini output/
..\..\bin\split binary data/sonic2app.exe STG47.ini output/
..\..\bin\split binary data/sonic2app.exe STG48.ini output/
..\..\bin\split binary data/sonic2app.exe STG49.ini output/
..\..\bin\split binary data/sonic2app.exe STG50.ini output/
..\..\bin\split binary data/sonic2app.exe STG51.ini output/
..\..\bin\split binary data/sonic2app.exe STG52.ini output/
..\..\bin\split binary data/sonic2app.exe STG53.ini output/
..\..\bin\split binary data/sonic2app.exe STG54.ini output/
..\..\bin\split binary data/sonic2app.exe STG55.ini output/
..\..\bin\split binary data/sonic2app.exe STG56.ini output/
..\..\bin\split binary data/sonic2app.exe STG57.ini output/
..\..\bin\split binary data/sonic2app.exe STG58.ini output/
..\..\bin\split binary data/sonic2app.exe STG59.ini output/
..\..\bin\split binary data/sonic2app.exe BOSS_GROBO_COMMON.ini output/
..\..\bin\split binary data/sonic2app.exe BOSS_BIGBOGY.ini output/
..\..\bin\split binary data/sonic2app.exe BOSS_BIGFOOT.ini output/
..\..\bin\split binary data/sonic2app.exe BOSS_FDOG.ini output/
..\..\bin\split binary data/sonic2app.exe BOSS_GOLEM.ini output/
..\..\bin\split binary data/sonic2app.exe BOSS_GOLEM_E.ini output/
..\..\bin\split binary data/sonic2app.exe BOSS_HOTSHOT.ini output/
..\..\bin\split binary data/sonic2app.exe BOSS_LAST1.ini output/
..\..\bin\split binary data/sonic2app.exe BOSS_LAST2.ini output/
..\..\bin\split binary data/sonic2app.exe CART.ini output/
..\..\bin\split binary data/sonic2app.exe ChaoCommon.ini output/
..\..\bin\split binary data/sonic2app.exe CHAOSTGDARK.ini output/
..\..\bin\split binary data/sonic2app.exe CHAOSTGHERO.ini output/
..\..\bin\split binary data/sonic2app.exe CHAOSTGNEUT.ini output/
..\..\bin\split binary data/sonic2app.exe CHAOSTGKINDER.ini output/
..\..\bin\split binary data/sonic2app.exe CHAOSTGRACE.ini output/
..\..\bin\split binary data/sonic2app.exe CHAOSTGKARATE.ini output/
..\..\bin\split binary data/sonic2app.exe ObjectLists.ini output/
..\..\bin\split binary data/sonic2app.exe Misc.ini output/
@echo Data_DLL split
..\..\bin\split binary data/resource/gd_PC/DLL/Win32/Data_DLL_Orig.dll ADVERTISE_DLL.ini output/
..\..\bin\split binary data/resource/gd_PC/DLL/Win32/Data_DLL_Orig.dll BOSS_GOLEM_DLL.ini output/
..\..\bin\split binary data/resource/gd_PC/DLL/Win32/Data_DLL_Orig.dll BOSS_GOLEM_E_DLL.ini output/
..\..\bin\split binary data/resource/gd_PC/DLL/Win32/Data_DLL_Orig.dll STG34_DLL.ini output/
..\..\bin\split binary data/resource/gd_PC/DLL/Win32/Data_DLL_Orig.dll CART_DLL.ini output/
..\..\bin\split binary data/resource/gd_PC/DLL/Win32/Data_DLL_Orig.dll Chao_DLL.ini output/
..\..\bin\split binary data/resource/gd_PC/DLL/Win32/Data_DLL_Orig.dll LeftoverDLL.ini output/