..\bin\split binary data/1ST_READ.bin newsplit/1ST_READ.ini output/
..\bin\split binary data/SONICADV/STG00.PRS newsplit/STG00.ini output/
..\bin\split binary data/SONICADV/STG01.PRS newsplit/STG01.ini output/
..\bin\split binary data/SONICADV/STG02.PRS newsplit/STG02.ini output/
..\bin\split binary data/SONICADV/STG03.PRS newsplit/STG03.ini output/
..\bin\split binary data/SONICADV/STG04.PRS newsplit/STG04.ini output/
..\bin\split binary data/SONICADV/STG05.PRS newsplit/STG05.ini output/
..\bin\split binary data/SONICADV/STG06.PRS newsplit/STG06.ini output/
..\bin\split binary data/SONICADV/STG07.PRS newsplit/STG07.ini output/
..\bin\split binary data/SONICADV/STG08.PRS newsplit/STG08.ini output/
..\bin\split binary data/SONICADV/STG09.PRS newsplit/STG09.ini output/
..\bin\split binary data/SONICADV/STG10.PRS newsplit/STG10.ini output/
..\bin\split binary data/SONICADV/STG12.PRS newsplit/STG12.ini output/
..\bin\split binary data/SONICADV/ADV00.PRS newsplit/ADV00.ini output/
..\bin\split binary data/SONICADV/ADV0100.PRS newsplit/ADV0100.ini output/
..\bin\split binary data/SONICADV/ADV0130.PRS newsplit/ADV0130.ini output/
..\bin\split binary data/SONICADV/ADV02.PRS newsplit/ADV02.ini output/
..\bin\split binary data/SONICADV/ADV03.PRS newsplit/ADV03.ini output/
..\bin\split binary data/SONICADV/B_CHAOS0.PRS newsplit/B_CHAOS0.ini output/
..\bin\split binary data/SONICADV/B_CHAOS2.PRS newsplit/B_CHAOS2.ini output/
..\bin\split binary data/SONICADV/B_CHAOS4.PRS newsplit/B_CHAOS4.ini output/
..\bin\split binary data/SONICADV/B_CHAOS6.PRS newsplit/B_CHAOS6.ini output/
..\bin\split binary data/SONICADV/B_CHAOS7.PRS newsplit/B_CHAOS7.ini output/
..\bin\split binary data/SONICADV/B_EGM1.PRS newsplit/B_EGM1.ini output/
..\bin\split binary data/SONICADV/B_EGM2.PRS newsplit/B_EGM2.ini output/
..\bin\split binary data/SONICADV/B_EGM3.PRS newsplit/B_EGM3.ini output/
..\bin\split binary data/SONICADV/B_ROBO.PRS newsplit/B_ROBO.ini output/
..\bin\split binary data/SONICADV/B_E101.PRS newsplit/B_E101.ini output/
..\bin\split binary data/SONICADV/B_E101_R.PRS newsplit/B_E101_R.ini output/
..\bin\split binary data/SONICADV/SHOOTING.PRS newsplit/SHOOTING.ini output/
..\bin\split binary data/SONICADV/SUMMARY.PRS newsplit/SUMMARY.ini output/
..\bin\split binary data/SONICADV/SBOARD.PRS newsplit/SBOARD.ini output/
..\bin\split binary data/SONICADV/MINICART.PRS newsplit/MINICART.ini output/
..\bin\split binary data/SONICADV/ADVERTISE.PRS newsplit/ADVERTISE.ini output/
..\bin\split binary data/SONICADV/AL_GARDEN00.PRS newsplit/AL_GARDEN00.ini output/
..\bin\split binary data/SONICADV/AL_GARDEN01.PRS newsplit/AL_GARDEN01.ini output/
..\bin\split binary data/SONICADV/AL_GARDEN02.PRS newsplit/AL_GARDEN02.ini output/
..\bin\split binary data/SONICADV/AL_RACE.PRS newsplit/AL_RACE.ini output/