..\bin\split binary data/1ST_READ.bin newsplit/1ST_READ.ini output/
..\bin\split binary data/SONICADV/STG01.PRS newsplit/STG01.ini output/
..\bin\split binary data/SONICADV/STG02.PRS newsplit/STG02.ini output/
..\bin\split binary data/SONICADV/STG03.PRS newsplit/STG03.ini output/
..\bin\split binary data/SONICADV/STG04.PRS newsplit/STG04.ini output/
..\bin\split binary data/SONICADV/STG05.PRS newsplit/STG05.ini output/
..\bin\split binary data/SONICADV/STG06.PRS newsplit/STG06.ini output/
..\bin\split binary data/SONICADV/STG07.PRS newsplit/STG07.ini output/
..\bin\split binary data/SONICADV/STG08.PRS newsplit/STG08.ini output/
..\bin\split binary data/SONICADV/STG09.PRS newsplit/STG09.ini output/
