@echo EXE split
..\bin\split binary data/sonic2app.exe newsplit/Characters.ini output/
..\bin\split binary data/sonic2app.exe newsplit/Enemies.ini output/
..\bin\split binary data/sonic2app.exe newsplit/CommonObjects.ini output/
..\bin\split binary data/sonic2app.exe newsplit/ADVERTISE.ini output/
..\bin\split binary data/sonic2app.exe newsplit/EMBLEMGET.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG00.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG03.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG04.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG05.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG06.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG07.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG08.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG09.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG10.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG11.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG12.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG13.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG14.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG15.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG16.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG17.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG18.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG19.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG20.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG21.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG22.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG23.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG24.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG25.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG26.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG27.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG28.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG29.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG30.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG31.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG32.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG33.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG34.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG35.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG36.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG37.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG38.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG39.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG40.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG41.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG42.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG43.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG44.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG45.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG46.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG47.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG48.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG49.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG50.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG51.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG52.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG53.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG54.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG55.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG56.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG57.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG58.ini output/
..\bin\split binary data/sonic2app.exe newsplit/STG59.ini output/
..\bin\split binary data/sonic2app.exe newsplit/BOSS_GROBO_COMMON.ini output/
..\bin\split binary data/sonic2app.exe newsplit/BOSS_BIGBOGY.ini output/
..\bin\split binary data/sonic2app.exe newsplit/BOSS_BIGFOOT.ini output/
..\bin\split binary data/sonic2app.exe newsplit/BOSS_FDOG.ini output/
..\bin\split binary data/sonic2app.exe newsplit/BOSS_GOLEM.ini output/
..\bin\split binary data/sonic2app.exe newsplit/BOSS_GOLEM_E.ini output/
..\bin\split binary data/sonic2app.exe newsplit/BOSS_HOTSHOT.ini output/
..\bin\split binary data/sonic2app.exe newsplit/BOSS_LAST1.ini output/
..\bin\split binary data/sonic2app.exe newsplit/BOSS_LAST2.ini output/
..\bin\split binary data/sonic2app.exe newsplit/CART.ini output/
..\bin\split binary data/sonic2app.exe newsplit/ChaoCommon.ini output/
..\bin\split binary data/sonic2app.exe newsplit/CHAOSTGDARK.ini output/
..\bin\split binary data/sonic2app.exe newsplit/CHAOSTGHERO.ini output/
..\bin\split binary data/sonic2app.exe newsplit/CHAOSTGNEUT.ini output/
..\bin\split binary data/sonic2app.exe newsplit/CHAOSTGKINDER.ini output/
..\bin\split binary data/sonic2app.exe newsplit/CHAOSTGRACE.ini output/
..\bin\split binary data/sonic2app.exe newsplit/CHAOSTGKARATE.ini output/
..\bin\split binary data/sonic2app.exe newsplit/ObjectLists.ini output/
@echo Event Data split
..\bin\split binary data/resource/gd_PC/event/tailsPlain.prs newsplit/TAILSPLAIN.ini output/
