..\bin\split mdl data\SONIC2\AMYMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\AMYMTN.PRS
..\bin\split mdl data\SONIC2\BKNUCKMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\KNUCKMTN.PRS
..\bin\split mdl data\SONIC2\BROUGEMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\ROUGEMTN.PRS
..\bin\split mdl data\SONIC2\BWALKMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\EWALKMTN.PRS
..\bin\split mdl data\SONIC2\CHAOS0MDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\CHAOS0MTN.PRS
..\bin\split mdl data\SONIC2\CWALKMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\CWALKMTN.PRS
..\bin\split mdl data\SONIC2\EGGMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\EGGMTN.PRS
..\bin\split mdl data\SONIC2\EWALK1MDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\EWALKMTN.PRS
..\bin\split mdl data\SONIC2\EWALKMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\EWALKMTN.PRS
..\bin\split mdl data\SONIC2\HEWALKMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\EWALKMTN.PRS
..\bin\split mdl data\SONIC2\HKNUCKMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\KNUCKMTN.PRS
..\bin\split mdl data\SONIC2\HROUGEMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\ROUGEMTN.PRS
..\bin\split mdl data\SONIC2\HSHADOWMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\TERIOSMTN.PRS
..\bin\split mdl data\SONIC2\HSONICMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\SONICMTN.PRS
..\bin\split mdl data\SONIC2\HTWALKMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\TWALKMTN.PRS
..\bin\split mdl data\SONIC2\KNUCKMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\KNUCKMTN.PRS
..\bin\split mdl data\SONIC2\METALSONICMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\METALSONICMTN.PRS
..\bin\split mdl data\SONIC2\MILESMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\MILESMTN.PRS
..\bin\split mdl data\SONIC2\PSOSHADOWMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\TERIOSMTN.PRS
..\bin\split mdl data\SONIC2\PSOSONICMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\SONICMTN.PRS
..\bin\split mdl data\SONIC2\ROUGEMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\ROUGEMTN.PRS
..\bin\split mdl data\SONIC2\SONICMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\SONICMTN.PRS
..\bin\split mdl data\SONIC2\SSHADOWMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS
..\bin\split mdl data\SONIC2\SSONICMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS
..\bin\split mdl data\SONIC2\TERIOSMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\TERIOSMTN.PRS
..\bin\split mdl data\SONIC2\TICALMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\TICALMTN.PRS
..\bin\split mdl data\SONIC2\TWALK1MDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\TWALKMTN.PRS
..\bin\split mdl data\SONIC2\TWALKMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\TWALKMTN.PRS
..\bin\split mdl data\SONIC2\XEWALKMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\EWALKMTN.PRS
..\bin\split mdl data\SONIC2\XKNUCKMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\KNUCKMTN.PRS
..\bin\split mdl data\SONIC2\XROUGEMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\ROUGEMTN.PRS
..\bin\split mdl data\SONIC2\XSHADOWMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\TERIOSMTN.PRS
..\bin\split mdl data\SONIC2\XSONICMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\SONICMTN.PRS
..\bin\split mdl data\SONIC2\XTWALKMDL.PRS output\Characters\ data\SONIC2\PLCOMMTN.PRS data\SONIC2\TWALKMTN.PRS