..\..\bin\split binary data/1ST_READ.bin 1ST_READ.ini output/
..\..\bin\split binary data/ADV00.PRS ADV00.ini output/
..\..\bin\split binary data/ADV0100.PRS ADV0100.ini output/
..\..\bin\split binary data/ADV0130.PRS ADV0130.ini output/
..\..\bin\split binary data/ADV02.PRS ADV02.ini output/
..\..\bin\split binary data/AL_GARDEN00.PRS AL_GARDEN00.ini output/
..\..\bin\split binary data/AL_GARDEN01.PRS AL_GARDEN01.ini output/
..\..\bin\split binary data/AL_GARDEN02.PRS AL_GARDEN02.ini output/
..\..\bin\split binary data/AL_RACE.PRS AL_RACE.ini output/
..\..\bin\split binary data/B_CHAOS0.PRS B_CHAOS0.ini output/
..\..\bin\split binary data/B_CHAOS2.PRS B_CHAOS2.ini output/
..\..\bin\split binary data/B_CHAOS4.PRS B_CHAOS4.ini output/
..\..\bin\split binary data/B_CHAOS7.PRS B_CHAOS7.ini output/
..\..\bin\split binary data/B_E101_R.PRS B_E101_R.ini output/
..\..\bin\split binary data/B_EGM1.PRS B_EGM1.ini output/
..\..\bin\split binary data/B_EGM3.PRS B_EGM3.ini output/
..\..\bin\split binary data/B_ROBO.PRS B_ROBO.ini output/
..\..\bin\split binary data/LAND1800.BIN LAND1800.ini output/
..\..\bin\split binary data/MINICART.PRS MINICART.ini output/
..\..\bin\split binary data/S_MOT.PRS S_MOT.ini output/
..\..\bin\split binary data/SBOARD.PRS SBOARD.ini output/
..\..\bin\split binary data/STG00.PRS STG00.ini output/
..\..\bin\split binary data/STG01.PRS STG01.ini output/
..\..\bin\split binary data/STG02.PRS STG02.ini output/
..\..\bin\split binary data/STG03.PRS STG03.ini output/
..\..\bin\split binary data/STG04.PRS STG04.ini output/
..\..\bin\split binary data/STG05.PRS STG05.ini output/
..\..\bin\split binary data/STG06.PRS STG06.ini output/
..\..\bin\split binary data/STG07.PRS STG07.ini output/
..\..\bin\split binary data/STG08.PRS STG08.ini output/
..\..\bin\split binary data/STG09.PRS STG09.ini output/
..\..\bin\split binary data/STG10.PRS STG10.ini output/