..\..\bin\split binary data/SonicApp.exe STG00.ini output/
..\..\bin\split binary data/SonicApp.exe STG01.ini output/
..\..\bin\split binary data/SonicApp.exe STG02.ini output/
..\..\bin\split binary data/SonicApp.exe STG03.ini output/
..\..\bin\split binary data/SonicApp.exe STG04.ini output/
..\..\bin\split binary data/SonicApp.exe STG05.ini output/
..\..\bin\split binary data/SonicApp.exe STG06.ini output/
..\..\bin\split binary data/SonicApp.exe STG07.ini output/
..\..\bin\split binary data/SonicApp.exe STG08.ini output/
..\..\bin\split binary data/SonicApp.exe STG09.ini output/
..\..\bin\split binary data/SonicApp.exe STG10.ini output/
..\..\bin\split binary data/SonicApp.exe STG12.ini output/
..\..\bin\split binary data/SonicApp.exe ADV00.ini output/
..\..\bin\split binary data/SonicApp.exe ADV0100.ini output/
..\..\bin\split binary data/SonicApp.exe ADV0130.ini output/
..\..\bin\split binary data/SonicApp.exe ADV02.ini output/
..\..\bin\split binary data/SonicApp.exe ADV03.ini output/
..\..\bin\split binary data/SonicApp.exe ADVERTISE.ini output/
..\..\bin\split binary data/SonicApp.exe Animals.ini output/
..\..\bin\split binary data/SonicApp.exe B_CHAOS0.ini output/
..\..\bin\split binary data/SonicApp.exe B_CHAOS2.ini output/
..\..\bin\split binary data/SonicApp.exe B_CHAOS4.ini output/
..\..\bin\split binary data/SonicApp.exe B_CHAOS6.ini output/
..\..\bin\split binary data/SonicApp.exe B_CHAOS7.ini output/
..\..\bin\split binary data/SonicApp.exe B_E101.ini output/
..\..\bin\split binary data/SonicApp.exe B_E101_R.ini output/
..\..\bin\split binary data/SonicApp.exe B_EGM1.ini output/
..\..\bin\split binary data/SonicApp.exe B_EGM2.ini output/
..\..\bin\split binary data/SonicApp.exe B_EGM3.ini output/
..\..\bin\split binary data/SonicApp.exe B_ROBO.ini output/
..\..\bin\split binary data/SonicApp.exe Chao.ini output/
..\..\bin\split binary data/SonicApp.exe Characters.ini output/
..\..\bin\split binary data/SonicApp.exe CommonObjects.ini output/
..\..\bin\split binary data/SonicApp.exe Debug.ini output/
..\..\bin\split binary data/SonicApp.exe Enemies.ini output/
..\..\bin\split binary data/SonicApp.exe EVENT.ini output/
..\..\bin\split binary data/SonicApp.exe Fish.ini output/
..\..\bin\split binary data/SonicApp.exe MINICART.ini output/
..\..\bin\split binary data/SonicApp.exe Mission.ini output/
..\..\bin\split binary data/SonicApp.exe SBOARD.ini output/
..\..\bin\split binary data/SonicApp.exe SHOOTING.ini output/