call manual_sa2dcmdl.bat

..\..\bin\split binary data/1ST_READ.bin 1ST_READ.ini output/
..\..\bin\split binary data/SONIC2/ADVERTISE.prs ADVERTISE.ini output/
..\..\bin\split binary data/SONIC2/EMBLEMGET.prs EMBLEMGET.ini output/
..\..\bin\split binary data/SONIC2/STG03.prs STG03.ini output/
..\..\bin\split binary data/SONIC2/STG04.prs STG04.ini output/
..\..\bin\split binary data/SONIC2/STG05.prs STG05.ini output/
..\..\bin\split binary data/SONIC2/STG06.prs STG06.ini output/
..\..\bin\split binary data/SONIC2/STG07.prs STG07.ini output/
..\..\bin\split binary data/SONIC2/STG08.prs STG08.ini output/
..\..\bin\split binary data/SONIC2/STG09.prs STG09.ini output/
..\..\bin\split binary data/SONIC2/STG10.prs STG10.ini output/
..\..\bin\split binary data/SONIC2/STG11.prs STG11.ini output/
..\..\bin\split binary data/SONIC2/STG12.prs STG12.ini output/
..\..\bin\split binary data/SONIC2/STG13.prs STG13.ini output/
..\..\bin\split binary data/SONIC2/STG14.prs STG14.ini output/
..\..\bin\split binary data/SONIC2/STG15.prs STG15.ini output/
..\..\bin\split binary data/SONIC2/STG16.prs STG16.ini output/
..\..\bin\split binary data/SONIC2/STG17.prs STG17.ini output/
..\..\bin\split binary data/SONIC2/STG18.prs STG18.ini output/
..\..\bin\split binary data/SONIC2/STG19.prs STG19.ini output/
..\..\bin\split binary data/SONIC2/STG20.prs STG20.ini output/
..\..\bin\split binary data/SONIC2/STG21.prs STG21.ini output/
..\..\bin\split binary data/SONIC2/STG22.prs STG22.ini output/
..\..\bin\split binary data/SONIC2/STG23.prs STG23.ini output/
..\..\bin\split binary data/SONIC2/STG24.prs STG24.ini output/
..\..\bin\split binary data/SONIC2/STG25.prs STG25.ini output/
..\..\bin\split binary data/SONIC2/STG26.prs STG26.ini output/
..\..\bin\split binary data/SONIC2/STG27.prs STG27.ini output/
..\..\bin\split binary data/SONIC2/STG28.prs STG28.ini output/
..\..\bin\split binary data/SONIC2/STG29.prs STG29.ini output/
..\..\bin\split binary data/SONIC2/STG30.prs STG30.ini output/
..\..\bin\split binary data/SONIC2/STG31.prs STG31.ini output/
..\..\bin\split binary data/SONIC2/STG32.prs STG32.ini output/
..\..\bin\split binary data/SONIC2/STG33.prs STG33.ini output/
..\..\bin\split binary data/SONIC2/STG34.prs STG34.ini output/
..\..\bin\split binary data/SONIC2/STG35.prs STG35.ini output/
..\..\bin\split binary data/SONIC2/STG36.prs STG36.ini output/
..\..\bin\split binary data/SONIC2/STG37.prs STG37.ini output/
..\..\bin\split binary data/SONIC2/STG38.prs STG38.ini output/
..\..\bin\split binary data/SONIC2/STG39.prs STG39.ini output/
..\..\bin\split binary data/SONIC2/STG40.prs STG40.ini output/
..\..\bin\split binary data/SONIC2/STG41.prs STG41.ini output/
..\..\bin\split binary data/SONIC2/STG42.prs STG42.ini output/
..\..\bin\split binary data/SONIC2/STG43.prs STG43.ini output/
..\..\bin\split binary data/SONIC2/STG44.prs STG44.ini output/
..\..\bin\split binary data/SONIC2/STG45.prs STG45.ini output/
..\..\bin\split binary data/SONIC2/BOSS_BIGBOGY.prs BOSS_BIGBOGY.ini output/
..\..\bin\split binary data/SONIC2/BOSS_BIGFOOT.prs BOSS_BIGFOOT.ini output/
..\..\bin\split binary data/SONIC2/BOSS_FDOG.prs BOSS_FDOG.ini output/
..\..\bin\split binary data/SONIC2/BOSS_GOLEM.prs BOSS_GOLEM.ini output/
..\..\bin\split binary data/SONIC2/BOSS_GOLEM_E.prs BOSS_GOLEM_E.ini output/
..\..\bin\split binary data/SONIC2/BOSS_HOTSHOT.prs BOSS_HOTSHOT.ini output/
..\..\bin\split binary data/SONIC2/BOSS_LAST1.prs BOSS_LAST1.ini output/
..\..\bin\split binary data/SONIC2/BOSS_LAST2.prs BOSS_LAST2.ini output/
..\..\bin\split binary data/SONIC2/CART.prs CART.ini output/
..\..\bin\split binary data/SONIC2/CHAO_MODEL.prs CHAO_MODEL.ini output/
..\..\bin\split binary data/SONIC2/CHAOSTGDARK.prs CHAOSTGDARK.ini output/
..\..\bin\split binary data/SONIC2/CHAOSTGENTRANCE.prs CHAOSTGENTRANCE.ini output/
..\..\bin\split binary data/SONIC2/CHAOSTGHERO.prs CHAOSTGHERO.ini output/
..\..\bin\split binary data/SONIC2/CHAOSTGKINDER.prs CHAOSTGKINDER.ini output/
..\..\bin\split binary data/SONIC2/CHAOSTGLOBBYLAND000.prs CHAOSTGLOBBYLAND000.ini output/
..\..\bin\split binary data/SONIC2/CHAOSTGLOBBYLAND00K.prs CHAOSTGLOBBYLAND00K.ini output/
..\..\bin\split binary data/SONIC2/CHAOSTGLOBBYLAND0DK.prs CHAOSTGLOBBYLAND0DK.ini output/
..\..\bin\split binary data/SONIC2/CHAOSTGLOBBYLANDH0K.prs CHAOSTGLOBBYLANDH0K.ini output/
..\..\bin\split binary data/SONIC2/CHAOSTGLOBBYLANDHDK.prs CHAOSTGLOBBYLANDHDK.ini output/
..\..\bin\split binary data/SONIC2/CHAOSTGNEUT.prs CHAOSTGNEUT.ini output/
..\..\bin\split binary data/SONIC2/CHAOSTGRACE.prs CHAOSTGRACE.ini output/
..\..\bin\split binary data/SONIC2/CHAOSTGRACELANDD.prs CHAOSTGRACELANDD.ini output/
..\..\bin\split binary data/SONIC2/CHAOSTGRACELANDH.prs CHAOSTGRACELANDH.ini output/
..\..\bin\split binary data/SONIC2/CHAOSTGRACELANDN.prs CHAOSTGRACELANDN.ini output/