[0]

[RING   ]
Name=Ring
Model=object/obj_ring.nja.sa1mdl
Texture=OBJ_REGULAR
GndDst=7
RotType=None
SclType=None

[SPRING ]
codefile=objdefs/Common/Spring.cs
codetype=SADXObjectDefinitions.Common.Spring
Name=Spring

[SPRINGB]
codefile=objdefs/Common/Spring.cs
codetype=SADXObjectDefinitions.Common.SpringB
Name=Rotatable Spring

[O AXPNL]
codefile=objdefs/Common/DashPanel.cs
codetype=SADXObjectDefinitions.Common.DashPanel
Name=Dash Panel

[O IRONB]
codefile=objdefs/Common/SwingSpikeBall.cs
codetype=SADXObjectDefinitions.Common.SwingSpikeBall
Name=Swinging Spike Ball

[O FeBJG]
codefile=objdefs/Common/FallSpikeBall.cs
codetype=SADXObjectDefinitions.Common.FallSpikeBall
Name=Falling Spike Ball

[O TOGE]
codefile=objdefs/Common/Spikes.cs
codetype=SADXObjectDefinitions.Common.Spikes
Name=Spikes

[O EME P]
Name=Emerald Shard
Model=object/obj_emekakera.nja.sa1mdl
Texture=OBJ_REGULAR
RotType=None
SclType=None

[O RELEASE]
Name=Capsule
Model=object/kaihoubox_body.nja.sa1mdl
Texture=OBJ_REGULAR
RotType=Y
SclType=None

[O SWITCH]
codefile=objdefs/Common/Switch.cs
codetype=SADXObjectDefinitions.Common.Switch
Name=Switch

[CMN KUSA]
codefile=objdefs/Common/Weed.cs
codetype=SADXObjectDefinitions.Common.Weed
Name=Weed

[CMN_DRING]
codefile=objdefs/Common/DashHoop.cs
codetype=SADXObjectDefinitions.Common.DashHoop
Name=Dash Hoop

[O BALOON]
Name=Balloon
Model=object/baloon_esc_baloon.nja.sa1mdl
Texture=OBJ_REGULAR
RotType=Y

[O ITEMBOX]
codefile=objdefs/Common/ItemBox.cs
codetype=SADXObjectDefinitions.Common.ItemBox
Name=Item Box

[O R_V]
Name=Rocket Platform Vertical
Model=object/rocket_launcher_body.nja.sa1mdl
Texture=OBJ_REGULAR
RotType=Y

[O R_VS]
Name=Rocket Platform Vertical Closed
Model=object/rocket_launcher_body.nja.sa1mdl
Texture=OBJ_REGULAR
RotType=Y

[O JPanel]
codefile=objdefs/Common/JumpPanel.cs
codetype=SADXObjectDefinitions.Common.JumpPanel
Name=Jump Panel

[O Save Point]
Name=Checkpoint
Model=object/savepoint_bmerge9.nja.sa1mdl
Texture=OBJ_REGULAR
RotType=ZXY
SclType=None

[WALL   ]
codefile=objdefs/Common/Wall.cs
codetype=SADXObjectDefinitions.Common.Wall
Name=Collision Wall

; REQUIRES CODE
[SCENE CHANGE]
Name=Scene Changer
Model=nondisp/hakoirimusume.nja.sa1mdl
RotType=None

; REQUIRES CODE
[O LINERING V]
Name=Line of Rings Vertical

; REQUIRES CODE
[O LINERING]
Name=Line of Rings

[O TRAIN]
Name=Train to the Mystic Ruins
Model=adv00_stationsquare/object/no_unite/train_base.nja.sa1mdl
Texture=SS_TRAIN
RotType=XYZ
SclType=None

[O POLE]
Name=Lamp Post
Model=adv00_stationsquare/object/sssikake_pole.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O KARTDOOR]
Name=Twinkle Park Entrance Door (Kart area)
Model=adv00_stationsquare/object/sssikake_kartdoor.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O SHOP1DOOR]
Name=Burger Shop Door
Model=adv00_stationsquare/object/sssikake_shop1door.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O SHOP2DOOR]
Name=Souvenir Shop Door
Model=adv00_stationsquare/object/sssikake_shop2door.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O TWINDOOR]
Name=Twinkle Park Entrance Door (Inside)
Model=adv00_stationsquare/object/sssikake_twindoor.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O URADOOR]
Name=Souvenir Shop Back Door
Model=adv00_stationsquare/object/sssikake_uradoor.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O TWADOOR]
Name=Twinkle Park Entrance Door (Station area)
Model=adv00_stationsquare/object/sssikake_twadoor.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O TWBDOOR]
Name=Twinkle Park Exit Door (Inside)
Model=adv00_stationsquare/object/sssikake_twbdoor.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O ELEVATOR]
Name=Twinkle Park Entrance Elevator
Model=adv00_stationsquare/object/sssikake_elevator.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O ELEBOX IN]
Name=Sewers Elevator (Inside)
Model=adv00_stationsquare/object/sssikake_gesuielebox.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O ELEBOX OUT]
Name=Sewers Elevator (Outside)
Model=adv00_stationsquare/object/sssikake_gesuielebox.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O EGGSTAND]
Name=Chao Egg Stand
Model=adv00_stationsquare/object/sssikake_eggstand.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O KOMONOBIN]
Name=Souvenir Shop Bottle
Model=adv00_stationsquare/object/bin_bin.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O KOMONOEXIT]
Name=Exit Sign
Model=adv00_stationsquare/object/ssobj_exit.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O KOMONOISUA]
Name=Souvenir Shop Chair A
Model=adv00_stationsquare/object/ssobj_isua.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O KOMONOISUB]
Name=Souvenir Shop Chair B
Model=adv00_stationsquare/object/ssobj_isub.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O KOMONOKEIKOTO]
Name=Ceiling Light (Long)
Model=adv00_stationsquare/object/keikoto_keikoto.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O KOMONORMLT]
Name=Ceiling Light (Round)
Model=adv00_stationsquare/object/ssobj_roomlight.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O BCLOCK]
Name=City Hall Clock
Model=adv00_stationsquare/object/ssobj_bigclock.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O S2SAKU]
Name=Souvenir Shop Fence
Model=adv00_stationsquare/object/sssikake_shop2saku.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O S1DNTO]
Name=Burger Shop Exterior Light
Model=adv00_stationsquare/object/no_unite/ssobj_shop1_dentou_d.nja.sa1mdl
Texture=SS_DENTOU
RotType=XYZ
SclType=None

[O S1SOLT]
Name=Burger Shop Items
Model=adv00_stationsquare/object/ssobj_shop1solt.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O S1KNBN]
Name=Burger Shop Billboard
Model=adv00_stationsquare/object/no_unite/ssobj_shop1_kanban.nja.sa1mdl
Texture=SS_KANBAN
RotType=XYZ
SclType=None

[O SIGNAL]
Name=Traffic Light
Model=adv00_stationsquare/object/ssobj_signal.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

[O CARD]
Name=Speed Highway Pass
Model=adv00_stationsquare/object/ssobj_card.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

[O S1 CHAIR]
Name=Burger Shop Chair
Model=adv00_stationsquare/object/ssobj_shop1chair.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O S2 KASEKI]
Name=Souvenir Shop Fossil
Model=adv00_stationsquare/object/ssobj_shop2_kaseki.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O S2 RADIO]
Name=Souvenir Shop Radio
Model=adv00_stationsquare/object/ssobj_shop2_radio.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O S2 ROBOT]
Name=Souvenir Shop Robot (Red)
Model=adv00_stationsquare/object/ssobj_shop2robot.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O S2 FRAME]
Name=Souvenir Shop Photo Frames
Model=adv00_stationsquare/object/ssobj_shop2frame.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O ELEKANBAN]
Name=Twinkle Park Billboard (Elevator)
Model=adv00_stationsquare/object/ssobj_elekanban.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O TWTESURI]
Name=Twinkle Park Entrance Handrails
Model=adv00_stationsquare/object/ssobj_twtesuri.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O TWKANBAN]
Name=Twinkle Park Billboard (Inside)
Model=adv00_stationsquare/object/no_unite/ssobj_twkanban.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O KARTKANBAN]
Name=Twinkle Circuit Billboard (Inside)
Model=adv00_stationsquare/object/no_unite/ssobj_kartkanban.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O BOAT]
Name=Boat to the Egg Carrier
Model=adv00_stationsquare/object/no_unite/sssikake_boatbody.nja.sa1mdl
Texture=SS_BOAT
RotType=XYZ
SclType=None

[O S2 AOROBOT]
Name=Souvenir Shop Robot (Blue)
Model=adv00_stationsquare/object/ssobj_shop2aorobot.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O S2 BOXFUTA]
Name=Souvenir Shop Cardboard Box Cover
Model=adv00_stationsquare/object/ssobj_shop2boxfuta.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O S2 BOXMI]
Name=Souvenir Shop Cardboard Box
Model=adv00_stationsquare/object/ssobj_shop2boxmi.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O STDOOR]
Name=Station Doors
Model=adv00_stationsquare/object/stdoor_stationdoor.nja.sa1mdl
Texture=OBJ_SS
IgnorePos=True
SclType=None
RotType=None

[O SYOUKAKI]
Name=Fire Hydrant
Model=adv00_stationsquare/object/ssobj_syoukaki.nja.sa1mdl
Texture=OBJ_SS
RotType=Y
SclType=None
IgnorePos=True

[O GAITOU]
Name=Street Light
Model=adv00_stationsquare/object/slights_gaitou.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

[O POOLCHAIR]
Name=Pool Chair
Model=adv00_stationsquare/object/ssobj_poolchair.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

[O PARASOL]
Name=Pool Parasol
Model=adv00_stationsquare/object/poolparasol_poolparasol.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

[O HWBSHUTTER]
Name=Speed Highway Entrance Shutter
Model=adv00_stationsquare/object/sssikake_hwbshutter.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

[O M SAKU]
Name=Emerald Coast Entrance Fence
Model=adv00_stationsquare/object/sssikake_kaigansaku.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

[O ROTYU]
Name=Parked Car (Manhole)
Model=adv00_stationsquare/object/no_unite/kuruma/ssrotyucar_body.nja.sa1mdl
Texture=SSCAR
RotType=Y

[O WAKUSEI]
Name=Planet Decoration (Twinkle Park Entrance)
Model=adv00_stationsquare/object/sssikake_wakusei.nja.sa1mdl
Texture=OBJ_SS
IgnorePos=True
RotType=None

[O HOTEL ELE]
Name=Hotel Elevator (to Chao Garden)
Model=adv00_stationsquare/object/sssikake_hotelele.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

[O TENBOU ELE]
Name=Hotel Elevator (to Chaos 2)
Model=adv00_stationsquare/object/sssikake_hotelele.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

[O HIGH ELE]
Name=Speed Highway Elevator
Model=adv00_stationsquare/object/sssikake_gesuielebox.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

[O ROUKA]
Name=O ROUKA (Deleted)

; NEEDS CODE TO DISPLAY POLICE CARS
[O BARRICADDE]
Name=City Hall Police Barricade
Model=adv00_stationsquare/object/sssikake_offbarri.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

[O HOTEL FRONT]
Name=Hotel Doors (Station Area)
Model=adv00_stationsquare/object/sscasinosikake_hnakagen.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

[O HOTEL BACK]
Name=Hotel Doors (Casino Area)
Model=adv00_stationsquare/object/sscasinosikake_hnakagen.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

[O HOTEL POOL]
Name=Hotel Doors (Pool Area)
Model=adv00_stationsquare/object/sscasinosikake_hnakagen.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

; REQUIRES CODE
[SCENE CHANGE SS]
Name=Scene Changer (Station Square)
Model=nondisp/hakoirimusume.nja.sa1mdl
RotType=None

[O STATION BACK]
Name=Casino Area Shutter
Model=adv00_stationsquare/object/no_unite/casino/sssikake_stationshutter.nja.sa1mdl
Texture=SS_CASINO
RotType=Y
AddYRot=4000

[O CASINO DOOR]
Name=Casino Door
Model=adv00_stationsquare/object/no_unite/casino/casinodoor_casinodoorwaku.nja.sa1mdl
Texture=SS_CASINO
RotType=XYZ

[O CASINO BUTTON]
Name=Casino Button
Model=adv00_stationsquare/object/no_unite/casino/sssikake_cajinobutton.nja.sa1mdl
Texture=SS_CASINO
RotType=XYZ

[O KEYICE]
Name=Ice Stone
Model=adv00_stationsquare/object/ssobj_keyice.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

[O KARTPASS]
Name=Twinkle Circuit Pass
Model=adv00_stationsquare/object/ssobj_pass.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

; NEEDS CODE TO RENDER 3 COPIES
[O OFFICE BARRICADE]
Name=City Hall Barricade (Knuckles)
Model=adv00_stationsquare/object/sssikake_offbarri.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

[O OFFICE DOOR]
Name=City Hall Entrance
Model=adv00_stationsquare/object/sssikake_officedoor.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

[O CONTAINER]
Name=Sewers Large Container
Model=adv00_stationsquare/object/sikake_containerbig.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

[O KEYBLOCK]
Name=Key Block (Big Pool Puzzle)
Model=adv00_stationsquare/object/sssikake_keyblock.nja.sa1mdl
Texture=OBJ_SS
RotType=Y

; REQUIRES CODE
[O PEOPLE]
Name=Station Square NPC
Model=adv00_stationsquare/object/oyaji_mdl_a.nja.sa1mdl
Texture=SS_PEOPLE
AddYPos=10
RotType=XYZ
SclType=None

; NEEDS MODEL FIX OR CODE
[O HINT]
Name=Hint Monitor
Model=object/hintbox_body.nja.sa1mdl
Texture=OBJ_REGULAR
RotType=XYZ
SclType=None

[C SPHERE]
codefile=objdefs/Common/Sphere.cs
codetype=SADXObjectDefinitions.Common.Sphere
Name=Collision Sphere

[C CYLINDER]
codefile=objdefs/Common/Cylinder.cs
codetype=SADXObjectDefinitions.Common.Cylinder
Name=Collision Cylinder

[C CUBE]
codefile=objdefs/Common/Cube.cs
codetype=SADXObjectDefinitions.Common.Cube
Name=Collision Cube

[OTTOTTO]
codefile=objdefs/Common/Ottoto.cs
codetype=SADXObjectDefinitions.Common.Ottoto
Name=Ottotto

[O ItemBoxAir]
codefile=objdefs/Common/ItemBox.cs
codetype=SADXObjectDefinitions.Common.FloatingItemBox
Name=Item Box (Air)

[O LevelItem]
Name=Character Upgrade Item
Model=object/luitem_itemget.nja.sa1mdl
Texture=OBJ_REGULAR
RotType=Y

[DL_KANBAN]
Name=Ring (DL_KANBAN)
Model=object/obj_ring.nja.sa1mdl
Texture=OBJ_REGULAR
GndDst=7

[O POWERBOX]
Name=Power Box (Unused)
Model=adv00_stationsquare/object/sikake_powerbox.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ
SclType=None

[O REALEGG]
Name=Gold Chao Egg
Model=adv00_stationsquare/object/ss_egg.nja.sa1mdl
Texture=OBJ_SS
RotType=Y
SclType=None

[O FAKEEGG]
Name=Fake Chao Egg
Model=adv00_stationsquare/object/nisetama_tamago.nja.sa1mdl
Texture=OBJ_SS
RotType=Y
SclType=None

[O CHAOCARD]
Name=Chao Stadium Pass (Unused)
Model=adv00_stationsquare/object/ssobj_chaocard.nja.sa1mdl
Texture=OBJ_SS
RotType=Y
SclType=None

[O HIDDENDOOR]
Name=Hotel Hidden Upstairs Door
Model=adv00_stationsquare/object/hotelsikake_hidndoor.nja.sa1mdl
Texture=OBJ_SS
RotType=Y
SclType=None

[O LIGHTCHANGER]
Name=Light Changer (Unused Object)
Model=nondisp/cube01.nja.sa1mdl
RotType=None

[O KARTCHANGER]
Name=Kart Changer (Unused Object)
Model=nondisp/hakoirimusume.nja.sa1mdl
RotType=None

; NEEDS CODE OR SPRITE
[O TIKAL]
Name=Tikal Hint
Model=
Texture=
RotType=XYZ
SclType=None

[BIGWJUMP]
codefile=objdefs/Emerald Coast/BigWJump.cs
codetype=SADXObjectDefinitions.EmeraldCoast.BigWJump

[O MANNEQUIN]
Name=Burger Shop Statue
Model=adv00_stationsquare/object/fatman_mdl_a.nja.sa1mdl
Texture=OBJ_SS
RotType=XYZ

[O EMBLEM]
Name=Emblem
RotType=XYZ
SclType=None
Model=object/o_emblm.nja.sa1mdl
Texture=EMBLEM