@echo Binary split
..\bin\split binary data\boot.dol boot.ini output\
..\bin\split binary data\advertiseD.rel advertiseD.ini output\
..\bin\split binary data\EmblemGetD.rel EmblemGetD.ini output\
..\bin\split binary data\eventD.rel eventD.ini output\
..\bin\split binary data\stg00D.rel stg00D.ini output\
..\bin\split binary data\stg03D.rel stg03D.ini output\
..\bin\split binary data\stg04D.rel stg04D.ini output\
..\bin\split binary data\stg05D.rel stg05D.ini output\
..\bin\split binary data\stg06D.rel stg06D.ini output\
..\bin\split binary data\stg07D.rel stg07D.ini output\
..\bin\split binary data\stg08D.rel stg08D.ini output\
..\bin\split binary data\stg09D.rel stg09D.ini output\
..\bin\split binary data\stg10D.rel stg10D.ini output\
..\bin\split binary data\stg11D.rel stg11D.ini output\
..\bin\split binary data\stg12D.rel stg12D.ini output\
..\bin\split binary data\stg13D.rel stg13D.ini output\
..\bin\split binary data\stg14D.rel stg14D.ini output\
..\bin\split binary data\stg15D.rel stg15D.ini output\
..\bin\split binary data\stg16D.rel stg16D.ini output\
..\bin\split binary data\stg17D.rel stg17D.ini output\
..\bin\split binary data\stg18D.rel stg18D.ini output\
..\bin\split binary data\stg19D.rel stg19D.ini output\
..\bin\split binary data\stg20D.rel stg20D.ini output\
..\bin\split binary data\stg21D.rel stg21D.ini output\
..\bin\split binary data\stg22D.rel stg22D.ini output\
..\bin\split binary data\stg23D.rel stg23D.ini output\
..\bin\split binary data\stg24D.rel stg24D.ini output\
..\bin\split binary data\stg25D.rel stg25D.ini output\
..\bin\split binary data\stg26D.rel stg26D.ini output\
..\bin\split binary data\stg27D.rel stg27D.ini output\
..\bin\split binary data\stg28D.rel stg28D.ini output\
..\bin\split binary data\stg29D.rel stg29D.ini output\
..\bin\split binary data\stg30D.rel stg30D.ini output\
..\bin\split binary data\stg31D.rel stg31D.ini output\
..\bin\split binary data\stg32D.rel stg32D.ini output\
..\bin\split binary data\stg33D.rel stg33D.ini output\
..\bin\split binary data\stg34D.rel stg34D.ini output\
..\bin\split binary data\stg35D.rel stg35D.ini output\
..\bin\split binary data\stg36D.rel stg36D.ini output\
..\bin\split binary data\stg37D.rel stg37D.ini output\
..\bin\split binary data\stg38D.rel stg38D.ini output\
..\bin\split binary data\stg39D.rel stg39D.ini output\
..\bin\split binary data\stg40D.rel stg40D.ini output\
..\bin\split binary data\stg41D.rel stg41D.ini output\
..\bin\split binary data\stg42D.rel stg42D.ini output\
..\bin\split binary data\stg43D.rel stg43D.ini output\
..\bin\split binary data\stg44D.rel stg44D.ini output\
..\bin\split binary data\stg45D.rel stg45D.ini output\
..\bin\split binary data\stg46D.rel stg46D.ini output\
..\bin\split binary data\stg47D.rel stg47D.ini output\
..\bin\split binary data\stg48D.rel stg48D.ini output\
..\bin\split binary data\stg49D.rel stg49D.ini output\
..\bin\split binary data\stg50D.rel stg50D.ini output\
..\bin\split binary data\stg51D.rel stg51D.ini output\
..\bin\split binary data\stg52D.rel stg52D.ini output\
..\bin\split binary data\stg53D.rel stg53D.ini output\
..\bin\split binary data\stg54D.rel stg54D.ini output\
..\bin\split binary data\stg55D.rel stg55D.ini output\
..\bin\split binary data\stg56D.rel stg56D.ini output\
..\bin\split binary data\stg57D.rel stg57D.ini output\
..\bin\split binary data\stg58D.rel stg58D.ini output\
..\bin\split binary data\stg59D.rel stg59D.ini output\
..\bin\split binary data\boss_bigbogyD.rel boss_bigbogyD.ini output\
..\bin\split binary data\boss_bigfootD.rel boss_bigfootD.ini output\
..\bin\split binary data\boss_fdogD.rel boss_fdogD.ini output\
..\bin\split binary data\Boss_GolemD.rel Boss_GolemD.ini output\
..\bin\split binary data\Boss_GolemED.rel Boss_GolemED.ini output\
..\bin\split binary data\boss_hotshotD.rel boss_hotshotD.ini output\
..\bin\split binary data\boss_last1D.rel boss_last1D.ini output\
..\bin\split binary data\Boss_Last2D.rel Boss_Last2D.ini output\
..\bin\split binary data\CartD.rel CartD.ini output\
..\bin\split binary data\ChaoMain.prs ChaoMain.ini output\
..\bin\split binary data\ChaoStgLobby.prs ChaoStgLobby.ini output\
..\bin\split binary data\ChaoStgLobby.rel ChaoStgLobbyREL.ini output\
..\bin\split binary data\ChaoStgLobby000.prs ChaoStgLobby000.ini output\
..\bin\split binary data\ChaoStgLobby00K.prs ChaoStgLobby00K.ini output\
..\bin\split binary data\ChaoStgLobby0DK.prs ChaoStgLobby0DK.ini output\
..\bin\split binary data\ChaoStgLobbyH0K.prs ChaoStgLobbyH0K.ini output\
..\bin\split binary data\ChaoStgLobbyHDK.prs ChaoStgLobbyHDK.ini output\
..\bin\split binary data\ChaoStgDark.prs ChaoStgDark.ini output\
..\bin\split binary data\ChaoStgNeut.prs ChaoStgNeut.ini output\
..\bin\split binary data\ChaoStgHero.prs ChaoStgHero.ini output\
..\bin\split binary data\ChaoStgEntrance.prs ChaoStgEntrance.ini output\
..\bin\split binary data\ChaoStgRace.prs ChaoStgRace.ini output\
..\bin\split binary data\ChaoStgRaceDark.prs ChaoStgRaceDark.ini output\
..\bin\split binary data\ChaoStgRaceNeut.prs ChaoStgRaceNeut.ini output\
..\bin\split binary data\ChaoStgRaceHero.prs ChaoStgRaceHero.ini output\
..\bin\split binary data\ChaoStgKinder.prs ChaoStgKinder.ini output\
..\bin\split binary data\ChaoStgOdekake.prs ChaoStgOdekake.ini output\
..\bin\split binary data\ChaoStgKarate.prs ChaoStgKarate.ini output\
..\bin\split binary data\ChaoStgStadium.prs ChaoStgStadium.ini output\